jobs:
- job: BuildMacOSWithSonarQube
  displayName: Build for macOS\XCode With SonarQube
  pool:
    vmImage: 'macos-latest'
  variables:
    SONARQUBE_HOST_URL: https://next.sonarqube.com/sonarqube
  steps:
  - task: SonarQubePrepare@5
    inputs:
      SonarQube: 'SonarQube' # Name of the SonarQube service endpoint you created
      scannerMode: 'CLI'
      configMode: 'file'
      extraProperties:
        "sonar.cfamily.compile-commands=build_wrapper_output_directory/compile_commands.json"
        # if you are using using SonarQube 10.5 or earlier, replace "sonar.cfamily.compile-commands=build_wrapper_output_directory/compile_commands.json" 
        # with "sonar.cfamily.build-wrapper-output=$BUILD_WRAPPER_OUT_DIR", as build-wrapper does not generate a compile_commands.json file before SonarQube 10.6
  - bash: |
      mkdir -p $HOME/.sonar
      curl -sSLo $HOME/.sonar/build-wrapper-macosx-x86.zip ${{variables.SONARQUBE_HOST_URL}}/static/cpp/build-wrapper-macosx-x86.zip
      unzip -o $HOME/.sonar/build-wrapper-macosx-x86.zip -d $HOME/.sonar/
    displayName: Download and install build wrapper
  - bash: |
      export PATH=$HOME/.sonar/build-wrapper-macosx-x86:$PATH
      build-wrapper-macosx-x86 --out-dir build_wrapper_output_directory xcodebuild
    workingDirectory: .
    displayName: Build in build-wrapper
  - task: SonarQubeAnalyze@5
    inputs:
      jdkversion: 'JAVA_HOME_17_X64'
